kh_online_shop_backend/kh_online_shop_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('promotion-banner/', include('promotion_banner.urls')),
    path('top-brands/', include('top_brands.urls')),
    path('product-category/', include('product_category.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kh_online_shop_backend/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name= "main_page"),
]

kh_online_shop_backend/product_category/urls.py
from django.urls import path
from . import views

app_name = "product_category"

urlpatterns = [
     path('', views.home_page, name="home_page"),
     path('view-page/', views.view_page, name="view_page"),
     path('update-page/<uuid:id>/', views.update_page, name="update_page"),
     path('delete_function/<uuid:id>/', views.delete_function, name="delete_function"),
     path('import_function/', views.import_function, name="import_function"),
]

kh_online_shop_backend/products/urls.py
from django.urls import path
from . import views
app_name = "products"

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('export-function/', views.export_function_2, name='export_function_2'),
    path('view-page/', views.view_page, name="view_page"),
    path('update-page/<uuid:id>/', views.update_page, name='update_page'),
    path('delete-page/<uuid:id>/', views.delete_page, name='delete_page'),
    path('search-by-type/<str:p_type>/', views.search_by_type, name='search_by_type'),
    path('search-by-brand/<str:p_brand>/', views.search_product_by_brand, name="search_product_by_brand"),
    path('get-data-by-pagination/', views.get_data_by_pagination, name="get_data_by_pagination"),
]

kh_online_shop_backend/promotion_banner/urls.py
from django.urls import path
from . import views

app_name = 'promotion_banner' 

urlpatterns = [
    path('', views.home_page, name= "home_page"),
    path('view-page/', views.view_page, name= "view_page"),
    path('update-page/<uuid:id>/', views.update_page, name= "update_page"),
    path('delete-data/<uuid:id>/', views.delete_data, name="delete_data"),
    path('get-promotion-banner/', views.get_promotion_banner, name="get_promotion_banner"),
]

kh_online_shop_backend/top_brands/urls.py
from django.urls import path
from . import views

app_name = 'top_brands' 

urlpatterns = [
    path('', views.add_brands, name= "add_brands"),
    path('view-page/', views.view_page, name= "view_page"),
    path('delete-page/<uuid:id>/', views.delete_page, name= "delete_page"),
    path('update-page/<uuid:id>/', views.update_page, name="update-page"),
    path('get-product-brand/', views.get_product_brand, name= "get_product_brand")
]

kh_online_shop_backend/products/models.py
from django.db import models
import uuid

class Products(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    detail = models.TextField(max_length=1500)
    upload_date = models.DateTimeField()
    product_type = models.CharField(max_length=20)
    product_brand = models.CharField(max_length=20)
    product_quantity = models.IntegerField(default=0)
        
    def __str__(self):
        return self.name

class ImageModel(models.Model):
    title = models.CharField(max_length=255)
    black_color = models.ImageField(upload_to="product_image_black", null=True, blank=True)
    white_color = models.ImageField(upload_to="product_image_white", null=True, blank=True)
    other_color_one = models.ImageField(upload_to="product_image_other_one")
    other_color_two = models.ImageField(upload_to="product_image_other_two")
    product = models.ForeignKey(Products, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.title

class PriceModel(models.Model):
    title = models.CharField(max_length=255)
    default_price = models.FloatField()
    discount_rate = models.FloatField()
    discount_price = models.FloatField()
    total_price = models.FloatField()
    product = models.ForeignKey(Products, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.title

class RatingStarModel(models.Model):
    title = models.CharField(max_length=255)
    total_stars = models.FloatField()
    user_rate = models.IntegerField()
    average_star = models.FloatField()
    product = models.ForeignKey(Products, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.title

class CommentModel(models.Model):
    title = models.CharField(max_length=255)
    user_name = models.CharField(max_length=255)
    comment_total = models.IntegerField()
    content = models.TextField(max_length=1500)
    product = models.ForeignKey(Products, on_delete=models.CASCADE, null=True, blank=True)
    
    def __str__(self):
        return self.title

kh_online_shop_backend/products/views.py
from django.http import JsonResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render, redirect
from datetime import datetime
from .models import Products, ImageModel, PriceModel, RatingStarModel
from django.core.paginator import Paginator,PageNotAnInteger, EmptyPage

date_time_now = datetime.now()
dt_string = date_time_now.strftime("%d/%m/%Y %H:%M:%S")

# Create your views here.
def home_page(request):
    if request.method == "POST":
        # 1 Product
        name = request.POST.get('name')
        product_detail = request.POST.get('product_detail')
        upload_date = datetime.strptime(dt_string, "%d/%m/%Y %H:%M:%S")
        product_type = request.POST.get('product_type')
        product_brand = request.POST.get('product_brand')
        product_quantity = request.POST.get('product_quantity')
        product = Products.objects.create(
            name = name, 
            detail = product_detail, 
            product_brand = product_brand, 
            product_type = product_type,
            upload_date = upload_date,
            product_quantity = product_quantity
            )
        product.save()
        
        # 2 Product Image
        if len(request.FILES) != 0:
            black_image = request.FILES.get('blakcolor')
            white_image = request.FILES.get('whitecolor')
            other_image_one = request.FILES.get('othercolorone')
            other_image_two = request.FILES.get('othercolortwo')
            
            image_title = f"{name} images"
            
            # Create ImageModel only if at least one image file is provided
            if any([black_image, white_image, other_image_one, other_image_two]):
                image = ImageModel.objects.create(
                    product=product,
                    black_color=black_image if black_image else None,
                    white_color=white_image if white_image else None,
                    other_color_one=other_image_one if other_image_one else None,
                    other_color_two=other_image_two if other_image_two else None,
                    title=image_title,
                )
                image.save()
        
        # 3 Product Price
        price = request.POST.get('price')
        discount_rating = request.POST.get('dicount-rate')
        price_title = f"{name} price"
        discount_price = (float(price) * float(discount_rating))/100
        total_price = float(price) - float(discount_price)
        product_price = PriceModel.objects.create(
            title = price_title,
            default_price = price,
            discount_rate = discount_rating,
            discount_price = discount_price,
            total_price = float('{:.2f}'.format(total_price)),
            product = product,
        )
        product_price.save()
        
        # 4 Product Rating Stars
        rating = request.POST.get('rating-star')
        title = f"{name} Rating"
        average_stars = float(rating) 
        user_rate = 1
        rating_star = RatingStarModel.objects.create(
            title = title,
            total_stars = rating,
            user_rate = user_rate,
            average_star = average_stars,
            product = product,
        )
        rating_star.save()
         
    return render(request, 'products/home_page.html')

def view_page(respone):
    data = Products.objects.all().prefetch_related('pricemodel_set', 'commentmodel_set', 'ratingstarmodel_set', 'imagemodel_set')
    return render(respone, 'products/view_page.html', {'data' : data})

def update_page(request, id):
    if request.method == "POST":
        name = request.POST['name']
        detail = request.POST['product_detail']
        type = request.POST['product_type']
        brand = request.POST['product_brand']
        qty = request.POST['product_quantity']
        
        black_image = request.FILES.get('blakcolor')
        white_image = request.FILES.get('whitecolor')
        other_image_one = request.FILES.get('othercolorone')
        other_image_two = request.FILES.get('othercolortwo')
        
        price = request.POST['price']
        discount_rate = request.POST['dicount_rate']
        discount_price = (float(price) * float(discount_rate))/100
        total_price = float(price) - float(discount_price)
        
        total_stars = request.POST['rating-star']
        user_rate = request.POST['user_rate']
        
        product = get_object_or_404(Products.objects.prefetch_related('pricemodel_set', 'commentmodel_set', 'ratingstarmodel_set', 'imagemodel_set'), id=id)
        
        product.name = name
        product.detail = detail
        product.product_type = type
        product.product_brand = brand
        product.product_quantity = qty
        product.save()

        # Update ImageModel
        images = product.imagemodel_set.first() 
        if images:
            if black_image:
                images.black_color = black_image
            if white_image:
                images.white_color = white_image
            if other_image_one:
                images.other_color_one = other_image_one
            if other_image_two:
                images.other_color_two = other_image_two
            images.save()

        # Update PriceModel
        prices = product.pricemodel_set.first()  
        if prices:
            prices.default_price = price
            prices.discount_rate = discount_rate
            prices.discount_price = "{:.2f}".format(float(discount_price))
            prices.total_price = total_price
            prices.save()

        # Update RatingStarModel
        ratings = product.ratingstarmodel_set.first()  
        try:
            average_star = "{:.2f}".format(float(total_stars) / float(user_rate) if user_rate != 0 else 0)
            ratings.total_stars = total_stars
            ratings.user_rate = user_rate
            ratings.average_star = average_star
            ratings.save()
        except ZeroDivisionError:
            ratings.average_star = 0.0
        finally:
            ratings.save()
                
        return redirect('products:view_page')
        
    # Use prefetch_related on the queryset
    queryset = Products.objects.prefetch_related('pricemodel_set', 'commentmodel_set', 'ratingstarmodel_set', 'imagemodel_set')
    old_data = get_object_or_404(queryset, id=id) 
    return render(request, 'products/update_page.html', {'old_data': old_data})

def delete_page(request, id):
    product = get_object_or_404(Products, id=id)
    product.delete()
    return redirect('products:view_page')

def export_function_2(request):
    products = Products.objects.all().prefetch_related('pricemodel_set', 'commentmodel_set', 'ratingstarmodel_set', 'imagemodel_set')
    data = [
        {
            'id': str(product.id),
            'name': product.name,
            'detail': product.detail,
            'upload_date': product.upload_date.strftime('%Y-%m-%d %H:%M:%S'),
            'product_type': product.product_type,
            'product_brand': product.product_brand,
            'product_quantity' : product.product_quantity,
            'comments': [
                {
                    'title': comment.title,
                    'user_name': comment.user_name,
                    'comment_total': comment.comment_total,
                    'content': comment.content,
                } for comment in product.commentmodel_set.all()
            ],
            'prices': [
                {
                    'title': price.title,
                    'default_price': price.default_price,
                    'discount_rate': price.discount_rate,
                    'discount_price': price.discount_price,
                    'total_price': price.total_price,
                } for price in product.pricemodel_set.all()
            ],
            'ratings': [
                {
                    'title': rating.title,
                    'total_stars': rating.total_stars,
                    'user_rate': rating.user_rate,
                    'average_star': rating.average_star,
                } for rating in product.ratingstarmodel_set.all()
            ],
            'images': [
                {
                    'black_color': request.build_absolute_uri(image.black_color.url) if image.black_color else None,
                    'white_color': request.build_absolute_uri(image.white_color.url) if image.white_color else None,
                    'other_color_one': request.build_absolute_uri(image.other_color_one.url) if image.other_color_one else None,
                    'other_color_two': request.build_absolute_uri(image.other_color_two.url) if image.other_color_two else None,
                } for image in product.imagemodel_set.all()
            ],
        } for product in products
    ]
    return JsonResponse(data, safe=False)

def search_by_type(request, p_type):
    products = get_list_or_404(Products.objects.prefetch_related('pricemodel_set', 'commentmodel_set', 'ratingstarmodel_set', 'imagemodel_set'), product_type=p_type)
    data = [
        {
            'id': str(product.id),
            'name': product.name,
            'detail': product.detail,
            'upload_date': product.upload_date.strftime('%Y-%m-%d %H:%M:%S'),
            'product_type': product.product_type,
            'product_brand': product.product_brand,
            'product_quantity': product.product_quantity,
            'comments': [
                {
                    'title': comment.title,
                    'user_name': comment.user_name,
                    'comment_total': comment.comment_total,
                    'content': comment.content,
                } for comment in product.commentmodel_set.all()
            ],
            'prices': [
                {
                    'title': price.title,
                    'default_price': price.default_price,
                    'discount_rate': price.discount_rate,

kh_online_shop_backend/products/templates/products/home_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add Product</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class= "bg-info d-flex align-items-center ps-5">
      <div>
        <a href="/" class = "text-white">Home Page</a>
      </div>
      <ul class="nav justify-content-end container">
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href=" {% url "promotion_banner:home_page" %} ">Promotion Banner</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href=" {% url "top_brands:add_brands" %} ">Brand</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href=" {% url "product_category:home_page" %} ">Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href=" {% url "products:home_page" %} ">Add Products</a>
          </li>
      </ul>
    </nav>
    <div class="container position-relative ">
      <div class = "position-absolute "> 
        <h1 class = "text-center mt-1">Add New Product</h1>
      <form action="" method="post" class = "mt-1" enctype = "multipart/form-data" id = "productform">
        {% csrf_token %}
        <div class="form-group ">
          <div class= "d-flex gap-3 ">
            <div class = "col-4">
                <label for="name">Product Name</label>
                <input type="text" name="name" id="name" class = "form-control " required>
            </div>
            <div class = "col-4">
                <label for="price">Product Price</label>
                <input type="number" name="price" id="price" class = "form-control " required step="any">
            </div>
            <div class = "col-4">
                <label for="dicount-rate">Discount Rate (%)</label>
            <br />
            <input type="number" name="dicount-rate" id="dicount-rate" class = "form-control" placeholder= "Discount Rate (%)" required value = 0.0 required step="any">
            </div>
            <div class = "col-4">
                <label for="rating-star">Rating Stars (1 -5)</label>
                <input type="number" name="rating-star" id="rating-star" class = "form-control" placeholder= "Rating Stars (1 - 5)" required value = 0.0 required step="0.5">
            </div>
          </div>
          <br />
          <div class = "d-flex gap-3">
            <div class = "col-4">
                <label for="">Product Type</label>
                <select class="form-select" aria-label="type" required name = "product_type">
                    <option value="Shoes">Shoes</option>
                    <option value="Shirt">Shirt</option>
                    <option value="Jacket">Jacket</option>
                    <option value="Sneaker">Sneaker</option>
                    <option value="Man">Man</option>
                    <option value="Woman">Woman</option>
                    <option value="T-Shirt">T-Shirt</option>
                    <option value="Electronic">Electronic</option>
                    <option value="Sport">Sport</option>
                    <option value="Children">Children</option>
                    <option value="Hat">Hat</option>
                    <option value="Cosmetic">Cosmetic</option>     
                    <option value="Jean">Jean</option>
                  </select>
            </div>
              <div class = "col-4">
                <label for="brand">Product Brand</label>
                <select class="form-select" aria-label="brand" required name = "product_brand">
                    <option value="ZARA">ZARA</option>
                    <option value="CHANEL">CHANEL</option>
                    <option value="ADIDAS">ADIDAS</option>
                    <option value="BRAND-A">BRAND-A</option>
                    <option value="BRAND-B">BRAND-B</option>
                    <option value="BRAND-C">BRAND-C</option>
                    <option value="DIOR">DIOR</option>
                    <option value="SAMSUNG">SAMSUNG</option>
                    <option value="OPPO">OPPO</option>
                    <option value="APPLE">APPLE</option>
                    <option value="NIKE">NIKE</option>
                    <option value="PRADA">PRADA</option>
                    <option value="HERMES">HERMES</option>
                    <option value="GUCCI">GUCCI</option>
                  </select>
              </div>
              <div class = "col-4">
                <label for="black-color">Black Color Image</label>
                <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "blakcolor" >
              </div>
              <div class = "col-4">
                <label for="white-color">White Color Image</label>
                <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "whitecolor" >
              </div>
          </div>
          <br />
          <div class="mb-3 d-flex gap-3">
            <div class = "col-4">
                <label for="other-color-one">Other Color One</label>
                <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "othercolorone" required>
            </div>
            <div class = "col-4">
                <label for="other-color-two">Other Color Two</label>
                <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "othercolortwo" required>
            </div>
            <div class = "col-4">
              <label for="product_quantity">Product Quantity</label>
              <br />
              <input class = "form-control" type="number" name="product_quantity" id="product_quantity" required>
            </div>
          </div>
          <br />
          <div class="form-floating">
            <textarea class="form-control" placeholder="Enter product detail" id="floatingTextarea2" style="height: 200px" required name = "product_detail"></textarea>
            <label for="floatingTextarea2">Product Detail</label>
          </div>
          <br />
          <div class="d-flex gap-3">
            <a class="btn btn-primary col-6" type="button" href= " {% url "products:view_page" %} ">View Promotion Banner List</a>
            <button class="btn btn-primary col-6" type="submit">Submit</button>
          </div>
        </div>
      </form>
      </div>
    </div>
    <script>
      document.getElementById('productform').onsubmit = function() {
        setTimeout(function() {
          document.getElementById('productform').reset();
        }, 1000);  // Adjust the timeout as needed to ensure the form is reset after submission
      };
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

kh_online_shop_backend/products/templates/products/view_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>View Product Category</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <h2 class= "text-center">All Product Categories Are Here</h2>
        <h4>By product Type</h4>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Man</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Woman Man</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Electronic</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Shoes</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Shirt</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Jacket</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Sneaker</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>T-Shirt</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Sport</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Children</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Travel-Kit</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Hat</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Cosmetic</a>
        <a href="#" class = 'btn btn-info me-3 mb-2 '>Sun-Glasses</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Jean</a>
        <h4>By product Brand</h4>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Brand-A</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Brand-B</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>Brand-C</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>ZARA</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>CHANEL</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>ADIDAS</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>DIOR</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>SAMSUNG</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>OPPO</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>APPLE</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>NIKE</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>PRADA</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>HERMES</a>
        <a href="#" class = 'btn btn-info me-3 mb-2'>GUCCI</a>
        <h4>Product ID</h4>
        <div class = "col-6">
            <input type="text" name="product_id" id="product_id" class = "mb-3 form-control">
            <a href="#" class = "btn btn-success pe-5 ps-5">Search</a>
        </div>
        <table class="table table-striped mt-3">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Product Detail
                    </th>
                    <th>
                        Action
                    </th>
                    
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                    <tr>
                        <td>{{ item.id }}</td>                     
                        <td>
                            <table class = "mb-2">
                                <tr>
                                    <td>
                                        {% for image in item.imagemodel_set.all %}
                                            {% if image.black_color %}
                                                <img src="{{ image.black_color.url }}" alt="product black color image" height="100px" class = "me-5">
                                            {% endif %}
                                            {% if image.white_color %}
                                                <img src="{{ image.white_color.url }}" alt="product white color image" height="100px" class = "me-5">
                                            {% endif %}
                                            {% if image.other_color_one %}
                                                <img src="{{ image.other_color_one.url }}" alt="product other color one image" height="100px" class = "me-5">
                                            {% endif %}
                                            {% if image.other_color_two %}
                                                <img src="{{ image.other_color_two.url }}" alt="product other color two image" height="100px" class = "me-5">
                                            {% endif %}
                                        {% endfor %}
                                    </td>
                                </tr>
                            </table>
                            <table class= "mb-2">
                                <tr>
                                    <td class = "pe-5">Name : {{ item.name }}</td>
                                    <td class = "pe-5">Type : {{ item.product_type }}</td>
                                    <td class = "pe-5">Brand : {{ item.product_brand }}</td>
                                    <td class = "pe-5">Quantity : {{ item.product_quantity }}</td>
                                </tr>
                            </table>
                            <table class = "mb-2">
                                {% for price in item.pricemodel_set.all %}
                                    <tr>
                                        <td class = "pe-5">Default Price : {{ price.default_price }}$ </td>
                                        <td class = "pe-5">Discount Rate : {{ price.discount_rate }}% </td>
                                        <td class = "pe-5">Discount Price : <span class = "text-warning">{{ price.discount_price }}$</span> </td>
                                        <td class = "pe-5">Total Price : <span class = "text-danger">{{ price.total_price }}$</span> </td>
                                    </tr>
                                {% endfor %}
                            </table>
                            <table class = 'mb-2'>
                                {% for rating in item.ratingstarmodel_set.all %}
                                    <tr>
                                        <td class= "pe-5">Total Stars {{ rating.total_stars }}</td>
                                        <td class= "pe-5">Users Rate {{ rating.user_rate }}</td>
                                        <td class= "pe-5">Averate Star  {{ rating.average_star }}</td>
                                    </tr>
                                {% endfor %}
                            </table>
                            <table >
                                <p class = "btn btn-success">View Comment</p>
                            </table>
                            <table >
                                <tr>
                                    <td>
                                        {{ item.detail }}
                                    </td>
                                </tr>
                            </table>
                        </td>
                        <td>
                            <a href=" {% url "products:update_page" id=item.id %} " class = "btn btn-warning">Update</a>
                            <br />
                            <br />
                            <a href=" {% url "products:delete_page" id=item.id %} " class = "btn btn-danger">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
              
            </tbody>
        </table>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>