kh_online_shop_backend/kh_online_shop_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('promotion-banner/', include('promotion_banner.urls')),
    path('top-brands/', include('top_brands.urls')),
    path('product-category/', include('product_category.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kh_online_shop_backend/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name= "main_page"),
]

kh_online_shop_backend/product_category/urls.py
from django.urls import path
from . import views

app_name = "product_category"

urlpatterns = [
     path('', views.home_page, name="home_page"),
     path('view-page/', views.view_page, name="view_page"),
     path('update-page/<uuid:id>/', views.update_page, name="update_page"),
     path('delete_function/<uuid:id>/', views.delete_function, name="delete_function"),
     path('import_function/', views.import_function, name="import_function"),
]

kh_online_shop_backend/products/urls.py
from django.urls import path
from . import views
app_name = "products"

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('export-function/', views.export_function_2, name='export_function_2'),
    path('view-page/', views.view_page, name="view_page"),
    path('update-page/<uuid:id>/', views.update_page, name='update_page'),
    path('delete-page/<uuid:id>/', views.delete_page, name='delete_page'),
    path('search-by-type/<str:p_type>/', views.search_by_type, name='search_by_type'),
    path('search-by-brand/<str:p_brand>/', views.search_product_by_brand, name="search_product_by_brand"),
    path('get-data-by-pagination/', views.get_data_by_pagination, name="get_data_by_pagination"),
]

kh_online_shop_backend/promotion_banner/urls.py
from django.urls import path
from . import views

app_name = 'promotion_banner' 

urlpatterns = [
    path('', views.home_page, name= "home_page"),
    path('view-page/', views.view_page, name= "view_page"),
    path('update-page/<uuid:id>/', views.update_page, name= "update_page"),
    path('delete-data/<uuid:id>/', views.delete_data, name="delete_data"),
    path('get-promotion-banner/', views.get_promotion_banner, name="get_promotion_banner"),
]

kh_online_shop_backend/top_brands/urls.py
from django.urls import path
from . import views

app_name = 'top_brands' 

urlpatterns = [
    path('', views.add_brands, name= "add_brands"),
    path('view-page/', views.view_page, name= "view_page"),
    path('delete-page/<uuid:id>/', views.delete_page, name= "delete_page"),
    path('update-page/<uuid:id>/', views.update_page, name="update-page"),
    path('get-product-brand/', views.get_product_brand, name= "get_product_brand")
]

kh_online_shop_backend/product_category/models.py
from django.db import models
import uuid

# Create your models here.
class ProductCategory(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length= 50)
    image = models.ImageField(upload_to="product_category_banner")
    upload_date = models.DateTimeField()
    
    def __str__(self):
        return self.name

kh_online_shop_backend/product_category/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import ProductCategory
from datetime import datetime

date_time_now = datetime.now()
dt_string = date_time_now.strftime("%d/%m/%Y %H:%M:%S")

# Create your views here.
def home_page(request):
    if request.method == "POST":
        data = ProductCategory()
        data.name = request.POST.get('name')
        data.upload_date = datetime.strptime(dt_string, "%d/%m/%Y %H:%M:%S")
        if len(request.FILES) != 0:
            data.image = request.FILES['image']
        data.save()
        return redirect('product_category:view_page')
    else :
        data = ProductCategory()
    return render(request, 'product_category/home_page.html')

def view_page(respone):
    data = ProductCategory.objects.all()
    return render(respone, 'product_category/view_page.html', {'data' : data})

def update_page(respone, id):
    if respone.method == 'POST':
        new_name = respone.POST['name']
        if len(respone.FILES) !=0 :
            image = respone.FILES['image']
        update = ProductCategory.objects.get(id=id)
        update.name = new_name
        update.upload_date = datetime.strptime(dt_string, "%d/%m/%Y %H:%M:%S")
        update.image = image
        update.save()
        return redirect('product_category:view_page')
        
    old_data = ProductCategory.objects.get(id=id)
    return render(respone, 'product_category/update_page.html', {'old_data' : old_data})

def delete_function(request, id):
    data = ProductCategory.objects.get(id = id)
    data.delete()
    return redirect('product_category:view_page')

def import_function(request):
    all_datas = ProductCategory.objects.all()
    data = [
        {
            'id' : str(all_data.id),
            'name' : all_data.name,
            'imageUrl' : request.build_absolute_uri(all_data.image.url)
        } for all_data in all_datas
    ]
    return JsonResponse(data, safe=False) 

kh_online_shop_backend/product_category/templates/product_category/home_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Product Category</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class= "bg-info d-flex align-items-center ps-5">
      <div>
        <a href="/" class = "text-white">Home Page</a>
      </div>
      <ul class="nav justify-content-end container">
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href=" {% url "promotion_banner:home_page" %} ">Promotion Banner</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href=" {% url "top_brands:add_brands" %} ">Brand</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href="#">Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href=" {% url "products:home_page" %} ">Add Products</a>
          </li>
      </ul>
    </nav>
    <div class="container position-relative">
      <div class = "position-absolute start-50 translate-middle-x mt-5"> 
        <h1 class = "text-center mt-3">Add New Product Category</h1>
      <form action="" method="post" class = "mt-3" enctype = "multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="name" id="name" class = "form-control" placeholder= "Enter Product Category Name" required>
          <br />
          <div class="mb-3">
            <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "image">
          </div>
          <br />
          <div class="d-grid">
            <button class="btn btn-primary" type="submit">Submit</button>
            <br />
            <a class="btn btn-primary" type="button" href= " {% url "product_category:view_page" %} ">View All Product Category List</a>
          </div>
        </div>
      </form>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

kh_online_shop_backend/product_category/templates/product_category/update_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Update Product Category</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container position-relative">
      <div class = "position-absolute start-50 translate-middle-x mt-2"> 
        <h1 class = "text-center mt-3">Update Product Category</h1>
      <form action="" method="post" class = "mt-3" enctype = "multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="name" id="name" class = "form-control" placeholder= "Enter Promotion Name" required value = {{old_data.name}}>
          <br />
            <img src="{{old_data.image.url}}" alt="Old product category image" height = "300px" width = "500px">
          <br />
          <br />
          <div class="mb-3">
            <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "image">
          </div>
          <div class="d-grid">
            <button class="btn btn-primary" type="submit">Submit</button>
          </div>
        </div>
      </form>
      <br />
      <br />
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

kh_online_shop_backend/product_category/templates/product_category/view_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>View Product Category</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <h2 class= "text-center">All Product Categories Are Here</h2>
        <table class="table table-striped mt-3">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Product Category Name
                    </th>
                    <th>
                        Image
                    </th>
                    <th>
                        Upload Date
                    </th>
                    <th>
                        Update
                    </th>
                    <th>
                        Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                <tr>
                    <td> {{item.id}} </td>
                    <td> {{item.name}} </td>
                    
                    <td>
                        <img src="{{item.image.url}}" alt="product category image" height = "100px">
                    </td>
                    <td> {{item.upload_date}} </td>
                    <td>
                        <a type="button" class="btn btn-outline-warning" href = " {% url "product_category:update_page" id=item.id %} ">Update</a>
                    </td>
                    <td>
                        <a type="button" class="btn btn-outline-danger" href = " {% url "product_category:delete_function" id=item.id %} ">Delete</a>
                    </td>
                </tr>
                {% endfor %}                
            </tbody>
        </table>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>