kh_online_shop_backend/kh_online_shop_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('promotion-banner/', include('promotion_banner.urls')),
    path('top-brands/', include('top_brands.urls')),
    path('product-category/', include('product_category.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kh_online_shop_backend/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name= "main_page"),
]

kh_online_shop_backend/product_category/urls.py
from django.urls import path
from . import views

app_name = "product_category"

urlpatterns = [
     path('', views.home_page, name="home_page"),
     path('view-page/', views.view_page, name="view_page"),
     path('update-page/<uuid:id>/', views.update_page, name="update_page"),
     path('delete_function/<uuid:id>/', views.delete_function, name="delete_function"),
     path('import_function/', views.import_function, name="import_function"),
]

kh_online_shop_backend/products/urls.py
from django.urls import path
from . import views
app_name = "products"

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('export-function/', views.export_function_2, name='export_function_2'),
    path('view-page/', views.view_page, name="view_page"),
    path('update-page/<uuid:id>/', views.update_page, name='update_page'),
    path('delete-page/<uuid:id>/', views.delete_page, name='delete_page'),
    path('search-by-type/<str:p_type>/', views.search_by_type, name='search_by_type'),
    path('search-by-brand/<str:p_brand>/', views.search_product_by_brand, name="search_product_by_brand"),
    path('get-data-by-pagination/', views.get_data_by_pagination, name="get_data_by_pagination"),
]

kh_online_shop_backend/promotion_banner/urls.py
from django.urls import path
from . import views

app_name = 'promotion_banner' 

urlpatterns = [
    path('', views.home_page, name= "home_page"),
    path('view-page/', views.view_page, name= "view_page"),
    path('update-page/<uuid:id>/', views.update_page, name= "update_page"),
    path('delete-data/<uuid:id>/', views.delete_data, name="delete_data"),
    path('get-promotion-banner/', views.get_promotion_banner, name="get_promotion_banner"),
]

kh_online_shop_backend/top_brands/urls.py
from django.urls import path
from . import views

app_name = 'top_brands' 

urlpatterns = [
    path('', views.add_brands, name= "add_brands"),
    path('view-page/', views.view_page, name= "view_page"),
    path('delete-page/<uuid:id>/', views.delete_page, name= "delete_page"),
    path('update-page/<uuid:id>/', views.update_page, name="update-page"),
    path('get-product-brand/', views.get_product_brand, name= "get_product_brand")
]

kh_online_shop_backend/top_brands/models.py
from django.db import models
import uuid

# Create your models here.
class TopBrand(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length= 50)
    banner = models.ImageField(upload_to='top_brand_banner')
    upload_time = models.DateTimeField()
    
    def __str__(self) :
        return self.name

kh_online_shop_backend/top_brands/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from .models import TopBrand
from datetime import datetime

date_time_now = datetime.now()
dt_string = date_time_now.strftime("%d/%m/%Y %H:%M:%S")
# Create your views here.
def add_brands(request):
    if request.method == "POST":
        data = TopBrand()
        data.name = request.POST.get('name')
        data.upload_time = datetime.strptime(dt_string, "%d/%m/%Y %H:%M:%S")
        if len(request.FILES) != 0 :
            data.banner = request.FILES['image']
            
        data.save()
        return redirect('top_brands:view_page')
    else :
        data = TopBrand()    
    return render(request, 'top_brands/home_page.html')

def view_page(request):
    data = TopBrand.objects.all()
    context = {
        "data" : data
    }
    return render (request, 'top_brands/view_page.html', context)

def delete_page(request, id):
    data = TopBrand.objects.get(id=id)
    data.delete()
    return redirect('top_brands:view_page')

def update_page(request, id):
    if request.method == "POST":
        name = request.POST['name']
        if len(request.FILES) !=0 :
            image = request.FILES['image']
        update = TopBrand.objects.get(id=id)
        update.name = name
        update.banner = image
        update.upload_time = datetime.strptime(dt_string, "%d/%m/%Y %H:%M:%S")
        update.save()
        return redirect('top_brands:view_page')
    
    datas = TopBrand.objects.get(id=id)
    return render (request, 'top_brands/update_page.html', {'datas' : datas})

def get_product_brand(request) :
    images = TopBrand.objects.all()
    data = [
        {
            "id": str(image.id),
            'name' : image.name,
            'imageUrl' : request.build_absolute_uri(image.banner.url)
        } for image in images
    ]
    return JsonResponse(data, safe=False)

kh_online_shop_backend/top_brands/templates/top_brands/home_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Top Brands</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class= "bg-info d-flex align-items-center ps-5">
      <div>
        <a href="/" class = "text-white">Home Page</a>
      </div>
      <ul class="nav justify-content-end container">
          <li class="nav-item">
            <a class="nav-link active text-white" aria-current="page" href=" {% url "promotion_banner:home_page" %} ">Promotion Banner</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href=" {% url "top_brands:add_brands" %} ">Brand</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href=" {% url "product_category:home_page" %} ">Category</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" href=" {% url "products:home_page" %} ">Add Products</a>
          </li>
      </ul>
    </nav>
    <div class="container position-relative">
      <div class = "position-absolute start-50 translate-middle-x mt-5"> 
        <h1 class = "text-center mt-3">Add New Brand Banner Here</h1>
      <form action="" method="post" class = "mt-3" enctype = "multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="name" id="name" class = "form-control" placeholder= "Enter Brand Name" required>
          <br />
          <div class="mb-3">
            <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "image">
          </div>
          <br />
          <div class="d-grid">
            <button class="btn btn-primary" type="submit">Submit</button>
            <br />
            <a class="btn btn-primary" type="button" href= " {% url "top_brands:view_page" %} " >View Brands List</a>
          </div>
        </div>
      </form>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

kh_online_shop_backend/top_brands/templates/top_brands/update_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Update Brand</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container position-relative">
      <div class = "position-absolute start-50 translate-middle-x mt-2"> 
        <h1 class = "text-center mt-3">Update Brand</h1>
      <form action="" method="post" class = "mt-3" enctype = "multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="name" id="name" class = "form-control" placeholder= "Enter Promotion Name" required value = {{datas.name}}>
          <br />
            <img src="{{datas.banner.url}}" alt="Old brand banner" height = "300px" width = "500px">
          <br />
          <br />
          <div class="mb-3">
            <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "image">
          </div>
          <div class="d-grid">
            <button class="btn btn-primary" type="submit">Submit</button>
          </div>
        </div>
      </form>
      <br />
      <br />
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

kh_online_shop_backend/top_brands/templates/top_brands/view_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>View Brands</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <h2 class= "text-center">All Top Brands Are Here</h2>
        <table class="table table-striped mt-3">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Brand Name
                    </th>
                    <th>
                        Banner
                    </th>
                    <th>
                        Upload Date
                    </th>
                    <th>
                        Update
                    </th>
                    <th>
                        Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for item in data %}
                <tr>
                    <td> {{item.id}} </td>
                    <td> {{item.name}} </td>
                    <td> {{item.upload_time}} </td>
                    <td>
                        <img src="{{item.banner.url}}" alt="brand banner" height = "100px">
                    </td>
                    <td>
                        <a type="button" class="btn btn-outline-warning" href = " {% url "top_brands:update-page" id=item.id %} ">Update</a>
                    </td>
                    <td>
                        <a type="button" class="btn btn-outline-danger" href = "{% url "top_brands:delete_page" id=item.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}                
            </tbody>
        </table>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>