kh_online_shop_backend/kh_online_shop_backend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('promotion-banner/', include('promotion_banner.urls')),
    path('top-brands/', include('top_brands.urls')),
    path('product-category/', include('product_category.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kh_online_shop_backend/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_page, name= "main_page"),
]

kh_online_shop_backend/promotion_banner/urls.py
from django.urls import path
from . import views

app_name = 'promotion_banner' 

urlpatterns = [
    path('', views.home_page, name= "home_page"),
    path('view-page/', views.view_page, name= "view_page"),
    path('update-page/<uuid:id>/', views.update_page, name= "update_page"),
    path('delete-data/<uuid:id>/', views.delete_data, name="delete_data"),
    path('get-promotion-banner/', views.get_promotion_banner, name="get_promotion_banner"),
]

kh_online_shop_backend/promotion_banner/models.py
from django.db import models
import uuid

class ImageModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to='promotion_banner')

    def __str__(self):
        return self.title

kh_online_shop_backend/promotion_banner/forms.py
# forms.py
from django import forms
from .models import ImageModel

class ImageForm(forms.ModelForm):
    class Meta:
        model = ImageModel
        fields = ['title', 'image']

kh_online_shop_backend/promotion_banner/views.py
from django.shortcuts import render, redirect
from .models import ImageModel
from django.http import JsonResponse

# Create your views here.
def home_page(request):
    if request.method == 'POST':
        promotion_banner_data = ImageModel()
        promotion_banner_data.title = request.POST.get('title')
        if len(request.FILES) != 0:
            promotion_banner_data.image = request.FILES['image']
        promotion_banner_data.save()
        return redirect('promotion_banner:view_page')
    else:
        promotion_banner_data = ImageModel()
    return render(request, 'promotion_banner/home_page.html')

def view_page(respone):
    promotion_banner_datas = ImageModel.objects.all()
    context  = {
        "promotion_banner_datas" : promotion_banner_datas
    }
    return render(respone, 'promotion_banner/view_page.html', context)

def update_page(respone, id):
    if respone.method == "POST":
        title = respone.POST['title']
        if len(respone.FILES) != 0:
            image = respone.FILES['image']
        update = ImageModel.objects.get(id=id)
        update.title = title
        update.image = image
        update.save()
        return redirect('promotion_banner:view_page')
    promotion_banner_datas = ImageModel.objects.get(id=id)
    return render(respone, 'promotion_banner/update_page.html', {"promotion_banner_datas" : promotion_banner_datas})

def delete_data(request, id):
    promotion_banner_datas = ImageModel.objects.get(id=id)
    promotion_banner_datas.delete()
    return redirect('promotion_banner:view_page')

def get_promotion_banner(request):
    images = ImageModel.objects.all()
    data = [
        {
            "id": str(image.id),
            "title": image.title,
            "image_url": request.build_absolute_uri(image.image.url)
        } for image in images
    ]
    return JsonResponse(data, safe=False)

kh_online_shop_backend/promotion_banner/templates/promotion_banner/home_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Promotion Banner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container position-relative">
      <div class = "position-absolute start-50 translate-middle-x mt-5"> 
        <h1 class = "text-center mt-3">Add New Promotion Banner</h1>
      <form action="" method="post" class = "mt-3" enctype = "multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="title" id="name" class = "form-control" placeholder= "Enter Promotion Name" required>
          <br />
          <div class="mb-3">
            <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "image">
          </div>
          <br />
          <div class="d-grid">
            <button class="btn btn-primary" type="submit">Submit</button>
          </div>
        </div>
      </form>
      <br />
      <br />
      <a class="btn btn-primary" type="button" href= "{% url "promotion_banner:view_page" %}">View Protion Banner List</a>
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

kh_online_shop_backend/promotion_banner/templates/promotion_banner/update_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Update Promotion Banner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container position-relative">
      <div class = "position-absolute start-50 translate-middle-x mt-2"> 
        <h1 class = "text-center mt-3">Update Promotion Banner</h1>
      <form action="" method="post" class = "mt-3" enctype = "multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <input type="text" name="title" id="name" class = "form-control" placeholder= "Enter Promotion Name" required value = {{promotion_banner_datas.title}}>
          <br />
            <img src="{{promotion_banner_datas.image.url}}" alt="Old promotion banner" height = "300px" width = "500px">
          <br />
          <br />
          <div class="mb-3">
            <input class="form-control" type="file" id="formFileMultiple" multiple placeholder = "Choose file" name = "image">
          </div>
          <div class="d-grid">
            <button class="btn btn-primary" type="submit">Submit</button>
          </div>
        </div>
      </form>
      <br />
      <br />
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

kh_online_shop_backend/promotion_banner/templates/promotion_banner/view_page.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>View Promotion Banner</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <h2 class= "text-center">All Promotion Banner Are Here</h2>
        <table class="table table-striped mt-3">
            <thead>
                <tr>
                    <th>
                        ID
                    </th>
                    <th>
                        Promotion Name
                    </th>
                    <th>
                        Promotion Banner
                    </th>
                    <th>
                        Update
                    </th>
                    <th>
                        Delete
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for item in promotion_banner_datas %}
                <tr>
                    <td> {{item.id}} </td>
                    <td> {{item.title}} </td>
                    <td>
                        <img src="{{item.image.url}}" alt="promotion banner" height = "100px">
                    </td>
                    <td>
                        <a type="button" class="btn btn-outline-warning" href = "{% url "promotion_banner:update_page" id=item.id %}">Update</a>
                    </td>
                    <td>
                        <a type="button" class="btn btn-outline-danger" href = "{% url "promotion_banner:delete_data" id=item.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}                
            </tbody>
        </table>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>